---
abstract: 'A Perl wrapper for the CLI Samtools suite of tools'
author:
  - 'Richard de Borja <richard.deborja@sickkids.ca>'
build_requires:
  Test::More: 0
configure_requires:
  Module::Build: 0
dynamic_config: 1
generated_by: 'Module::Build version 0.4205, CPAN::Meta::Converter version 2.120921'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: NGS-Tools-Samtools
provides:
  NGS::Tools::Samtools:
    file: lib/NGS/Tools/Samtools.pm
    version: 0.02
  NGS::Tools::Samtools::Role::Pileup:
    file: lib/NGS/Tools/Samtools/Role/Pileup.pm
    version: 0
resources:
  license: http://www.perlfoundation.org/artistic_license_2_0
version: 0.02
